"""Scenario: attachment-driven analysis + tests + toolchain, then a data-driven report.

Selector: ``attachment_report`` (or ``all``).

Built to validate **sampling parameters** (doc/QUANT_SAMPLING.md) — the first
scenario built around this. This file is content-only (see
:mod:`kodo.validator._scenario`); the LLM under test, its knob selection, and the
judge are pinned by whatever runs it — see :mod:`kodo.validator.suites` for a
shipped pin. A knob selection resolves to ``llama-server``'s launch config,
so a run measures exactly what a user gets by choosing those settings in the
sidebar's Configure modal. Re-run the same scenario against a different
``LLMUnderTest.knobs``
to compare presets.

It chains the four things a lossy quant tends to break, in one pipeline:

1. **Reading an attachment.** The entire specification lives in an attached
   ``spec.md``, staged *outside* the workspace, so ``read_attachment`` is the
   only way to reach it — and that requires reproducing the attachment's UUID
   verbatim from context. This is the direct regression test for the DRY bug
   (DRY-enabled sampling made exactly this impossible; QUANT_SAMPLING.md §3f),
   and the RVP scores it as a pass/fail gate worth the whole run.
2. **Building something with tests and a toolchain.** Multi-part enough to
   clear Problem Solver's small-ask fast path, so it should route through
   ``planner`` and come back with ``toolchain_builder`` and ``developer``
   steps — same trigger shape as the ``toolchain`` family.
3. **Reading a produced file back off disk.** ``results.json`` is generated by
   the run's own code, so its contents cannot be known in advance from the
   prompt — the second turn has to actually read it.
4. **Deciding from that file's content.** The report's above/below split is
   derived from numbers the model cannot guess, so a hallucinated report is
   detectable.

``data.csv`` is fixed, so the whole run has one correct answer: region totals
north 758.00, south 925.50, east 677.50, west 997.50, central 1239.75, mean
919.65 → above = {south, west, central}, below = {north, east}. Deliberately
not guessable from the region names, and deliberately arranged so the mean of
the region totals differs from the mean of the individual rows (a common
mis-implementation the RVP calls out). Keep ``data.csv`` and the RVP's expected
numbers in sync — the RVP hardcodes them as its ground truth.

No seed is pinned, on purpose: a single deterministic run says nothing about
robustness, so preset comparisons should run this several times and read the
pass rate rather than trusting one score.
"""

from __future__ import annotations

from kodo.validator import Modes, RootSpec, Scenario
from kodo.validator.prompts import PROMPTS

# Ten rows over five regions. Totals are units x unit_price summed per region;
# see the module docstring for the resulting ground truth (mirrored in the RVP).
_DATA_CSV = """\
region,units,unit_price
north,120,4.25
north,80,3.10
south,45,12.60
south,30,11.95
east,200,1.85
east,150,2.05
west,60,7.40
west,90,6.15
central,25,19.99
central,40,18.50
"""

SCENARIO = Scenario(
    name="attachment-report",
    prompts=[
        PROMPTS.get("attachment_report/task"),
        PROMPTS.get("attachment_report/report_task"),
    ],
    # spec.md rides on the first prompt only; the second turn works from
    # results.json on disk.
    attachments={0: [PROMPTS.path("attachment_report/spec")]},
    user_proxy_prompt=PROMPTS.get("attachment_report/upp"),
    result_validation_prompt=PROMPTS.get("attachment_report/rvp"),
    roots=[RootSpec(name="revenue-analysis", files={"data.csv": _DATA_CSV})],
    # Interactive + problem-solving with friction-free gates: the spec is
    # complete (no ask_user expected — the UPP is a safety net that refuses to
    # dictate the spec), and the explicit tests + toolchain asks are what make
    # Problem Solver plan and spawn toolchain_builder/developer.
    modes=Modes(
        autonomous=False,
        workflow="problem_solving",
        edit_control="allow_all",
        command_control="permissive",
    ),
    turn_timeout=3600.0,
    eval_timeout=3000.0,
)
