"""Hardcoded Gemma4-31B GGUF catalog entries."""

from __future__ import annotations

from ._types import LocalLLMEntry


def gemma4_31b_entries() -> list[LocalLLMEntry]:
    return [
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-q8-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-Q8_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-Q8_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q8_K_XL",
            size_hint="35 GB",
            gpu_tip="~40GB total at 128K context. An 8GB GPU (e.g. RTX 4060 Ti) plus a 48GB DDR5 "
            "kit covers it — llama.cpp splits this dense model layer-by-layer between GPU and CPU.",
            mac_tip="Needs ~40GB — fits a 48GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably; "
            "a 64GB config gives more headroom.",
            min_memory=48,
            memory=48,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-q8-0",
            kind="hardcoded_hf",
            description="Gemma 4 31B Q8_0 by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-Q8_0.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="Q8_0",
            size_hint="32.6 GB",
            gpu_tip="~38GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus a 48GB DDR5 "
            "kit is enough, with llama.cpp's layer offloading filling in the gap.",
            mac_tip="Needs ~38GB — fits a 48GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably.",
            min_memory=48,
            memory=48,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-q6-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-Q6_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-Q6_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q6_K_XL",
            size_hint="27.5 GB",
            gpu_tip="~33GB total at 128K context. An 8GB GPU (e.g. RTX 5060) plus ~32GB of DDR5 "
            "system RAM covers it — llama.cpp keeps as many layers on the GPU as fit and runs the "
            "rest from RAM.",
            mac_tip="Needs ~33GB — fits a 48GB MacBook Pro comfortably; a 36GB M4 Max or M5 Max is "
            "tight.",
            min_memory=32,
            memory=48,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-q5-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-Q5_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-Q5_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q5_K_XL",
            size_hint="21.9 GB",
            gpu_tip="~27GB total at 128K context. An 8GB GPU (e.g. RX 7600) plus a 32GB DDR5 kit "
            "is enough, with llama.cpp's layer offloading filling in the gap.",
            mac_tip="Needs ~27GB — fits a 32GB MacBook Pro comfortably, or a 48GB config with "
            "headroom to spare.",
            min_memory=32,
            memory=48,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-q4-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-Q4_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-Q4_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q4_K_XL",
            size_hint="18.8 GB",
            gpu_tip="~24GB total at 128K context. An 8GB GPU (e.g. RTX 4060) plus a 24GB DDR5 kit "
            "covers it comfortably — a typical gaming rig once llama.cpp splits the layers.",
            mac_tip="Needs ~24GB — fits a 32GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=24,
            memory=32,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-q3-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-Q3_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-Q3_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q3_K_XL",
            size_hint="15.4 GB",
            gpu_tip="~20GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus a 24GB DDR5 "
            "kit covers it, with llama.cpp's layer offloading handling the rest.",
            mac_tip="Needs ~20GB — fits a 32GB MacBook Pro (M4 or M5) comfortably; a 24GB config "
            "is tight.",
            min_memory=24,
            memory=32,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-q2-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-Q2_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-Q2_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q2_K_XL",
            size_hint="11.8 GB",
            gpu_tip="~17GB total at 128K context. An 8GB GPU (e.g. RX 7600) plus a 16GB DDR5 kit "
            "covers it comfortably.",
            mac_tip="Needs ~17GB — fits a 24GB MacBook Pro comfortably; a 16GB M5 is tight.",
            min_memory=16,
            memory=16,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-iq3-xxs",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-IQ3_XXs by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-IQ3_XXS.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-IQ3_XXS",
            size_hint="11.8 GB",
            gpu_tip="~17GB total at 128K context. An 8GB GPU (e.g. RTX 5060) plus a 16GB DDR5 kit "
            "covers it comfortably.",
            mac_tip="Needs ~17GB — fits a 24GB MacBook Pro comfortably; a 16GB M5 is tight.",
            min_memory=16,
            memory=16,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-31b-ud-iq2-xxs",
            kind="hardcoded_hf",
            description="Gemma 4 31B UD-IQ2_XXS by Unsloth",
            repo_id="unsloth/gemma-4-31B-it-GGUF",
            filename="gemma-4-31B-it-UD-IQ2_XXS.gguf",
            context_window=262_144,
            base_llm="Gemma4-31B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-IQ2_XXS",
            size_hint="8.5 GB",
            gpu_tip="~14GB total at 128K context. Any 8GB GPU (e.g. RTX 4060) plus a 16GB DDR5 "
            "kit handles this, the smallest of the Gemma 4 31B builds.",
            mac_tip="Needs ~14GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=16,
            memory=16,
            llamacpp_version=8720,
        ),
    ]
