"""Nemotron35-Lightning-30B-A3B GGUF catalog entries."""

from __future__ import annotations

from ._knobs_shared import KV_CACHE_F16_DEFAULT, SHARED_KNOBS
from ._types import LocalLLMEntry


def nemotron35_30b_a3b_entries() -> list[LocalLLMEntry]:
    return [
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-bf16",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B BF16 by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-bf16/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-bf16-00001-of-00002.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            knob_defaults=KV_CACHE_F16_DEFAULT,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="BF16",
            size_hint="65.9 GB",
            gpu_tip="~68GB total, even at the full 262K context — Nemotron 3.5 is a hybrid "
            "Mamba/MoE architecture (only 6 of 52 layers are full attention, with just 2 KV "
            "heads), so unlike a dense model this size KV cache barely grows with context; the "
            "total is essentially the BF16 file size plus a small state-space margin. A 16GB GPU "
            "(e.g. RTX 4080) plus a 64GB DDR5 kit covers it, with llama.cpp offloading the "
            "inactive routed experts to system RAM.",
            mac_tip="Needs ~68GB — comfortable on a 96GB M4 Max/M5 Max.",
            min_memory=96,
            memory=96,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q8_0",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q8_0 by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q8_0.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q8_0",
            size_hint="35.0 GB",
            gpu_tip="~36GB total, and that number barely moves with context length — Nemotron "
            "3.5's hybrid Mamba/MoE design keeps KV cache tiny (only 6 attention layers, 2 KV "
            "heads) even at its full 262K window. An 8GB GPU (e.g. RTX 4060 Ti) plus ~32GB of "
            "DDR5 system RAM covers it via llama.cpp's MoE expert offloading.",
            mac_tip="Needs ~36GB — fits a 48GB MacBook Pro comfortably; tight on 36GB.",
            min_memory=36,
            memory=48,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q6_k_l",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q6_K_L by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q6_K_L.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q6_K_L",
            size_hint="34.3 GB",
            gpu_tip="~36GB total. Same hybrid-architecture math as the Q8_0 build above — "
            "Nemotron 3.5's few attention layers keep context nearly free memory-wise. An 8GB "
            "GPU (e.g. RTX 3060 Ti) plus ~32GB of DDR5 system RAM handles it comfortably.",
            mac_tip="Needs ~36GB — fits a 48GB MacBook Pro comfortably; tight on 36GB.",
            min_memory=36,
            memory=48,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q5_k_l",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q5_K_L by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q5_K_L.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q5_K_L",
            size_hint="27.1 GB",
            gpu_tip="~29GB total — Nemotron 3.5's hybrid Mamba/MoE layers keep that number "
            "close to the file size regardless of context length. An 8GB GPU (e.g. RTX 5060) "
            "plus ~24GB of DDR5 system RAM is enough, with llama.cpp offloading the routed "
            "experts.",
            mac_tip="Needs ~29GB — fits a 32GB MacBook Pro comfortably.",
            min_memory=32,
            memory=32,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q5_k_s",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q5_K_S by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q5_K_S.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q5_K_S",
            size_hint="24.8 GB",
            gpu_tip="~26GB total. An 8GB GPU (e.g. RX 7600) plus ~24GB of DDR5 system RAM "
            "covers it — Nemotron 3.5's hybrid architecture means the full 262K context adds "
            "almost nothing on top.",
            mac_tip="Needs ~26GB — fits a 32GB MacBook Pro comfortably.",
            min_memory=32,
            memory=32,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q4_k_l",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q4_K_L by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_K_L.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q4_K_L",
            size_hint="25.6 GB",
            gpu_tip="~27GB total. An 8GB GPU (e.g. RTX 4060) plus ~24GB of DDR5 system RAM "
            "covers the whole model via llama.cpp's layer/expert offloading.",
            mac_tip="Needs ~27GB — fits a 32GB MacBook Pro comfortably.",
            min_memory=32,
            memory=32,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q4_k_s",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q4_K_S by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_K_S.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q4_K_S",
            size_hint="23.2 GB",
            gpu_tip="~25GB total. An 8GB GPU (e.g. RTX 4060 Ti) plus ~24GB of DDR5 system RAM "
            "is enough — llama.cpp's MoE expert offloading keeps this close to full-GPU speed.",
            mac_tip="Needs ~25GB — fits a 32GB MacBook Pro comfortably.",
            min_memory=32,
            memory=32,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q4_1",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q4_1 by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_1.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q4_1",
            size_hint="20.9 GB",
            gpu_tip="~22GB total. An 8GB GPU (e.g. RTX 3060 Ti) plus a 24GB DDR5 kit covers "
            "it comfortably.",
            mac_tip="Needs ~22GB — fits a 24GB MacBook Pro; a 32GB config is safer.",
            min_memory=24,
            memory=32,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-q4_0",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B Q4_0 by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-Q4_0.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="Q4_0",
            size_hint="19.1 GB",
            gpu_tip="~21GB total. An 8GB GPU (e.g. RTX 5060) plus a 24GB DDR5 kit covers it "
            "comfortably.",
            mac_tip="Needs ~21GB — fits a 24GB MacBook Pro; a 32GB config is safer.",
            min_memory=24,
            memory=24,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-iq4_nl",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B IQ4_NL by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-IQ4_NL.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="IQ4_NL",
            size_hint="18.9 GB",
            gpu_tip="~20GB total. An 8GB GPU (e.g. RX 7600) plus a 24GB DDR5 kit covers it "
            "comfortably.",
            mac_tip="Needs ~20GB — fits a 24GB MacBook Pro; a 32GB config is safer.",
            min_memory=24,
            memory=24,
            llamacpp_version=10362,
        ),
        LocalLLMEntry(
            name="nvidia-nemottron35-30b-a3b-iq4_xs",
            kind="hardcoded_hf",
            description="Nvidia Nemotron 3.5 30B A3B IQ4_XS by bartowski",
            repo_id="bartowski/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF",
            filename="NVIDIA-Nemotron-3.5-Lightning-30B-A3B-IQ4_XS.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Nemotron35-30B-A3B",
            llm_author="Nvidia Corporation",
            license_name="OpenMDW-1.1",
            license_url="https://openmdw.ai/license/1-1/",
            quant_author="bartowski",
            quant_type="IQ4_XS",
            size_hint="18.9 GB",
            gpu_tip="~20GB total. An 8GB GPU (e.g. RTX 4060) plus a 24GB DDR5 kit covers it "
            "comfortably.",
            mac_tip="Needs ~20GB — fits a 24GB MacBook Pro; a 32GB config is safer.",
            min_memory=24,
            memory=24,
            llamacpp_version=10362,
        ),
    ]
