"""Qwen3-Coder-Next-80B GGUF catalog entries."""

from __future__ import annotations

from ._knobs_shared import SHARED_KNOBS
from ._types import LocalLLMEntry


def qwen3_coder_next_80b_entries() -> list[LocalLLMEntry]:
    return [
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q8-k-xl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q8_K_XL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="UD-Q8_K_XL/Qwen3-Coder-Next-UD-Q8_K_XL-00001-of-00003.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q8_K_XL",
            size_hint="86.3 GB",
            gpu_tip="~90GB total at 128K context — the biggest of the Qwen 3 Coder Next 80B "
            "builds. A 16GB GPU (e.g. RTX 4080) handles the shared layers at full speed while "
            "llama.cpp's MoE expert offloading pushes the rest onto a 96GB DDR5 kit.",
            mac_tip="Needs ~90GB — comfortable on a 128GB MacBook Pro (M4 Max or M5 Max).",
            min_memory=128,
            memory=128,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q8-0",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q8_0 by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Q8_0/Qwen3-Coder-Next-Q8_0-00001-of-00003.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q8_0",
            size_hint="84.8 GB",
            gpu_tip="~89GB total at 128K context. A 16GB GPU (e.g. RTX 5080) keeps the shared "
            "layers fast, with llama.cpp offloading the rest of the experts to a 96GB DDR5 kit.",
            mac_tip="Needs ~89GB — comfortable on a 128GB MacBook Pro (M4 Max or M5 Max).",
            min_memory=128,
            memory=128,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q6-k-xl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q6_K_XL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="UD-Q6_K_XL/Qwen3-Coder-Next-UD-Q6_K_XL-00001-of-00003.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q6_K_XL",
            size_hint="73.1 GB",
            gpu_tip="~77GB total at 128K context. A 16GB GPU (e.g. RTX 4070 Ti Super) handles the "
            "shared layers, and llama.cpp's MoE offloading covers the rest with a 96GB DDR5 kit.",
            mac_tip="Needs ~77GB — exceeds a 64GB MacBook Pro; a 128GB M4 Max or M5 Max is "
            "required.",
            min_memory=128,
            memory=128,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q6-k",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q6_K by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="UD-Q6_K/Qwen3-Coder-Next-UD-Q6_K-00001-of-00003.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q6_K",
            size_hint="65.8 GB",
            gpu_tip="~70GB total at 128K context. A 16GB GPU (e.g. RX 7900 GRE) handles the shared "
            "layers, and llama.cpp's MoE offloading covers the rest with a 96GB DDR5 kit.",
            mac_tip="Needs ~70GB — exceeds a 64GB MacBook Pro; a 128GB M4 Max or M5 Max is "
            "required.",
            min_memory=128,
            memory=128,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q5-k-xl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q5_K_XL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="UD-Q5_K_XL/Qwen3-Coder-Next-UD-Q5_K_XL-00001-of-00003.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q5_K_XL",
            size_hint="59.5 GB",
            gpu_tip="~64GB total at 128K context. A 16GB GPU (e.g. RTX 5070 Ti) handles the shared "
            "layers, and llama.cpp's MoE offloading covers the rest with a 64GB DDR5 kit.",
            mac_tip="Needs ~64GB — right at the edge of a 64GB MacBook Pro; a 128GB M4 Max or M5 "
            "Max gives more headroom.",
            min_memory=64,
            memory=128,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q5-k-s",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q5_K_S by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="UD-Q5_K_S/Qwen3-Coder-Next-UD-Q5_K_S-00001-of-00003.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q5_K_S",
            size_hint="55.8 GB",
            gpu_tip="~60GB total at 128K context. A 16GB GPU (e.g. RX 7800 XT) handles the shared "
            "layers, and llama.cpp's MoE offloading covers the rest with a 48GB DDR5 kit.",
            mac_tip="Needs ~60GB — tight on a 64GB MacBook Pro; a 128GB M4 Max or M5 Max gives "
            "more headroom.",
            min_memory=64,
            memory=64,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q4-k-xl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q4_K_XL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-Q4_K_XL.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q4_K_XL",
            size_hint="49.6 GB",
            gpu_tip="~54GB total at 128K context. It's an 80B model, but the MoE architecture "
            "still plays nice with offloading: a 16GB GPU (e.g. RTX 4060 Ti 16GB) keeps the shared "
            "layers fast while ~48GB of DDR5 system RAM absorbs the rest of the experts.",
            mac_tip="Needs ~54GB — tight on a 64GB MacBook Pro; a 128GB M4 Max or M5 Max is the "
            "safe choice.",
            min_memory=64,
            memory=64,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-mxfp4-moe",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B MXFP4-MOE by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-MXFP4_MOE.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="MXFP4_MOE",
            size_hint="48.0 GB",
            gpu_tip="~52GB total at 128K context. A 16GB GPU (e.g. RTX 5070 Ti) handles the "
            "always-on layers, and ~48GB of DDR5 system RAM covers the offloaded MXFP4 experts — "
            "llama.cpp's MoE offloading keeps speed close to a full-VRAM fit.",
            mac_tip="Needs ~52GB — tight on a 64GB MacBook Pro; a 128GB M4 Max or M5 Max gives "
            "more headroom.",
            min_memory=64,
            memory=64,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-iq4-nl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-IQ4_NL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-IQ4_NL.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-IQ4_NL",
            size_hint="39.2 GB",
            gpu_tip="~43GB total at 128K context. A 16GB GPU (e.g. RTX 4060 Ti 16GB) keeps the "
            "shared layers fast, and llama.cpp's MoE expert offloading covers the rest with a "
            "32GB DDR5 kit.",
            mac_tip="Needs ~43GB — fits a 64GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably; "
            "a 48GB config is tight.",
            min_memory=48,
            memory=48,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-iq4-xs",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-IQ4_XS by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-IQ4_XS.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-IQ4_XS",
            size_hint="38.4 GB",
            gpu_tip="~42GB total at 128K context. A 16GB GPU (e.g. RTX 5070 Ti) keeps the shared "
            "layers fast, and llama.cpp's MoE expert offloading covers the rest with a 32GB "
            "DDR5 kit.",
            mac_tip="Needs ~42GB — fits a 64GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably; "
            "a 48GB config is tight.",
            min_memory=48,
            memory=48,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q3-k-xl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q3_K_XL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-Q3_K_XL.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q3_K_XL",
            size_hint="36.3 GB",
            gpu_tip="~40GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus ~48GB of DDR5 "
            "system RAM is enough — llama.cpp's MoE expert offloading keeps this 80B model fast "
            "without a workstation card.",
            mac_tip="Needs ~40GB — fits a 64GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably; "
            "a 48GB config is tight.",
            min_memory=48,
            memory=64,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-iq3-s",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-IQ3_S by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-IQ3_S.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-IQ3_S",
            size_hint="29.7 GB",
            gpu_tip="~34GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus ~32GB of DDR5 "
            "system RAM is enough — llama.cpp's MoE expert offloading keeps this 80B model fast "
            "without a workstation card.",
            mac_tip="Needs ~34GB — fits a 48GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably.",
            min_memory=32,
            memory=48,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-iq3-xxs",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-IQ3_XXS by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-IQ3_XXS.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-IQ3_XXS",
            size_hint="28.5 GB",
            gpu_tip="~33GB total at 128K context. An 8GB GPU (e.g. RTX 4060) plus ~32GB of DDR5 "
            "system RAM is enough, with llama.cpp's MoE offloading keeping this close to "
            "full-GPU speed.",
            mac_tip="Needs ~33GB — fits a 48GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably.",
            min_memory=32,
            memory=48,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-q2-k-xl",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-Q2_K_XL by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-Q2_K_XL.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-Q2_K_XL",
            size_hint="26.8 GB",
            gpu_tip="~31GB total at 128K context. An 8GB GPU (e.g. RTX 5060) plus a 32GB DDR5 kit "
            "is enough — llama.cpp's MoE expert offloading keeps this 80B model fast on modest "
            "hardware.",
            mac_tip="Needs ~31GB — fits a 32GB MacBook Pro (M4 or M5) if you trim context a bit, "
            "or a 48GB config (M4 Pro/Max or M5 Pro/Max) comfortably.",
            min_memory=32,
            memory=32,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-iq2-m",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-IQ2_M by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-IQ2_M.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-IQ2_M",
            size_hint="25 GB",
            gpu_tip="~29GB total at 128K context. An 8GB GPU (e.g. RX 7600) plus a 32GB DDR5 kit "
            "covers it comfortably, with llama.cpp's MoE offloading doing the heavy lifting.",
            mac_tip="Needs ~29GB — fits a 32GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=32,
            memory=48,
            llamacpp_version=5092,
        ),
        LocalLLMEntry(
            name="unsloth-qwen3-coder-next-80b-iq2-xxs",
            kind="hardcoded_hf",
            description="Qwen 3 Coder 80B UD-IQ2_XXS by Unsloth",
            repo_id="unsloth/Qwen3-Coder-Next-GGUF",
            filename="Qwen3-Coder-Next-UD-IQ2_XXS.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            base_llm="Qwen3-Coder-Next-80B",
            llm_author="Alibaba Cloud",
            quant_author="Unsloth",
            quant_type="UD-IQ2_XXS",
            size_hint="23.3 GB",
            gpu_tip="~27GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus a 32GB DDR5 "
            "kit is enough — the smallest of the Qwen 3 Coder Next 80B builds, and llama.cpp's "
            "MoE offloading keeps it fast even on modest hardware.",
            mac_tip="Needs ~27GB — fits a 32GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=32,
            memory=48,
            llamacpp_version=5092,
        ),
    ]
