"""Ornith10-9B GGUF catalog entries."""

from __future__ import annotations

from ._knobs_qwen import QWEN_MOE_CONTEXT_KNOB
from ._knobs_shared import SHARED_KNOBS
from ._types import LocalLLMEntry


def ornith10_9b_entries() -> list[LocalLLMEntry]:
    return [
        LocalLLMEntry(
            name="deepreinforce-ornith10-9b-bf16",
            kind="hardcoded_hf",
            description="Ornith 1.0 9B BF16 by DeepReinforce",
            repo_id="deepreinforce-ai/Ornith-1.0-9B-GGUF",
            filename="ornith-1.0-9b-bf16.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS + (QWEN_MOE_CONTEXT_KNOB,),
            base_llm="Ornith10-9B",
            llm_author="DeepReinforce AI",
            quant_author="DeepReinforce AI",
            quant_type="BF16",
            size_hint="17.9 GB",
            gpu_tip="",
            mac_tip="",
            min_memory=24,
            memory=24,
            llamacpp_version=9831,
        ),
        LocalLLMEntry(
            name="deepreinforce-ornith10-9b-q8-0",
            kind="hardcoded_hf",
            description="Ornith 1.0 9B Q8_0 by DeepReinforce",
            repo_id="deepreinforce-ai/Ornith-1.0-9B-GGUF",
            filename="ornith-1.0-9b-Q8_0.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS + (QWEN_MOE_CONTEXT_KNOB,),
            base_llm="Ornith10-9B",
            llm_author="DeepReinforce AI",
            quant_author="DeepReinforce AI",
            quant_type="Q8_0",
            size_hint="9.53 GB",
            gpu_tip="",
            mac_tip="",
            min_memory=12,
            memory=16,
            llamacpp_version=9831,
        ),
        LocalLLMEntry(
            name="deepreinforce-ornith10-9b-q6-k",
            kind="hardcoded_hf",
            description="Ornith 1.0 9B Q6_K by DeepReinforce",
            repo_id="deepreinforce-ai/Ornith-1.0-9B-GGUF",
            filename="ornith-1.0-9b-Q6_K.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS + (QWEN_MOE_CONTEXT_KNOB,),
            base_llm="Ornith10-9B",
            llm_author="DeepReinforce AI",
            quant_author="DeepReinforce AI",
            quant_type="Q6_K",
            size_hint="7.36 GB",
            gpu_tip="",
            mac_tip="",
            min_memory=12,
            memory=16,
            llamacpp_version=9831,
        ),
        LocalLLMEntry(
            name="deepreinforce-ornith10-9b-q5-k-m",
            kind="hardcoded_hf",
            description="Ornith 1.0 9B Q5_K_M by DeepReinforce",
            repo_id="deepreinforce-ai/Ornith-1.0-9B-GGUF",
            filename="ornith-1.0-9b-Q5_K_M.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS + (QWEN_MOE_CONTEXT_KNOB,),
            base_llm="Ornith10-9B",
            llm_author="DeepReinforce AI",
            quant_author="DeepReinforce AI",
            quant_type="Q5_K_M",
            size_hint="6.47 GB",
            gpu_tip="",
            mac_tip="",
            min_memory=8,
            memory=12,
            llamacpp_version=9831,
        ),
        LocalLLMEntry(
            name="deepreinforce-ornith10-9b-q4-k-m",
            kind="hardcoded_hf",
            description="Ornith 1.0 9B Q4_K_M by DeepReinforce",
            repo_id="deepreinforce-ai/Ornith-1.0-9B-GGUF",
            filename="ornith-1.0-9b-Q4_K_M.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS + (QWEN_MOE_CONTEXT_KNOB,),
            base_llm="Ornith10-9B",
            llm_author="DeepReinforce AI",
            quant_author="DeepReinforce AI",
            quant_type="Q4_K_M",
            size_hint="5.63 GB",
            gpu_tip="",
            mac_tip="",
            min_memory=8,
            memory=12,
            llamacpp_version=9831,
        ),
    ]
