"""Nanbiege42-3B GGUF catalog entries."""

from __future__ import annotations

from ._knobs_qwen import QWEN_MOE_CONTEXT_KNOB
from ._knobs_shared import KV_CACHE_F16_DEFAULT, SHARED_KNOBS
from ._types import LocalLLMEntry


def nanbiege42_3b_entries() -> list[LocalLLMEntry]:
    return [
        LocalLLMEntry(
            name="bartowski-nanbiege42-3b-bf16",
            kind="hardcoded_hf",
            description="Nanbiege 4.2 3B BF16 by bartowski",
            repo_id="bartowski/Nanbeige_Nanbeige4.2-3B-GGUF",
            filename="Nanbeige_Nanbeige4.2-3B-bf16.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            knob_defaults=KV_CACHE_F16_DEFAULT,
            base_llm="Nanbeige4.2-3B",
            llm_author="Nanbiege LLM Lab",
            quant_author="bartowski",
            quant_type="BF16",
            size_hint="8.34 GB",
            gpu_tip="~12GB total at 128K context — small enough to fit entirely on a 16GB GPU "
            "(e.g. RTX 4060 Ti 16GB), no CPU offload needed even for the unquantized BF16 build.",
            mac_tip="Needs ~12GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=12,
            memory=16,
            llamacpp_version=10159,
        ),
        LocalLLMEntry(
            name="bartowski-nanbiege42-3b-q8_0",
            kind="hardcoded_hf",
            description="Nanbiege 4.2 3B Q8_0 by bartowski",
            repo_id="bartowski/Nanbeige_Nanbeige4.2-3B-GGUF",
            filename="Nanbeige_Nanbeige4.2-3B-Q8_0.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            knob_defaults=KV_CACHE_F16_DEFAULT,
            base_llm="Nanbeige4.2-3B",
            llm_author="Nanbiege LLM Lab",
            quant_author="bartowski",
            quant_type="Q8_0",
            size_hint="4.43 GB",
            gpu_tip="~8.5GB total at 128K context — just over a strict 8GB card, but comfortably "
            "fits a 16GB GPU (e.g. RTX 4060) with plenty of headroom.",
            mac_tip="Needs ~8.5GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=8,
            memory=12,
            llamacpp_version=10159,
        ),
        LocalLLMEntry(
            name="bartowski-nanbiege42-3b-q6_k_l",
            kind="hardcoded_hf",
            description="Nanbiege 4.2 3B Q6_K_L by bartowski",
            repo_id="bartowski/Nanbeige_Nanbeige4.2-3B-GGUF",
            filename="Nanbeige_Nanbeige4.2-3B-Q6_K_L.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            knob_defaults=KV_CACHE_F16_DEFAULT,
            base_llm="Nanbeige4.2-3B",
            llm_author="Nanbiege LLM Lab",
            quant_author="bartowski",
            quant_type="Q6_K_L",
            size_hint="3.84 GB",
            gpu_tip="~8GB total at 128K context — small enough to fit entirely on an 8GB GPU "
            "(e.g. RTX 3060 Ti), no CPU offload needed.",
            mac_tip="Needs ~8GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=8,
            memory=12,
            llamacpp_version=10159,
        ),
        LocalLLMEntry(
            name="bartowski-nanbiege42-3b-q5_k_l",
            kind="hardcoded_hf",
            description="Nanbiege 4.2 3B Q5_K_L by bartowski",
            repo_id="bartowski/Nanbeige_Nanbeige4.2-3B-GGUF",
            filename="Nanbeige_Nanbeige4.2-3B-Q5_K_L.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            knob_defaults=KV_CACHE_F16_DEFAULT,
            base_llm="Nanbeige4.2-3B",
            llm_author="Nanbiege LLM Lab",
            quant_author="bartowski",
            quant_type="Q5_K_L",
            size_hint="3.39 GB",
            gpu_tip="~7.5GB total at 128K context — comfortably fits an 8GB GPU (e.g. RTX 5060).",
            mac_tip="Needs ~7.5GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=8,
            memory=12,
            llamacpp_version=10159,
        ),
        LocalLLMEntry(
            name="bartowski-nanbiege42-3b-q4_k_l",
            kind="hardcoded_hf",
            description="Nanbiege 4.2 3B Q4_K_L by bartowski",
            repo_id="bartowski/Nanbeige_Nanbeige4.2-3B-GGUF",
            filename="Nanbeige_Nanbeige4.2-3B-Q4_K_L.gguf",
            context_window=262_144,
            knobs=SHARED_KNOBS,
            knob_defaults=KV_CACHE_F16_DEFAULT,
            base_llm="Nanbeige4.2-3B",
            llm_author="Nanbiege LLM Lab",
            quant_author="bartowski",
            quant_type="Q4_K_L",
            size_hint="3.06 GB",
            gpu_tip="~7GB total at 128K context — the smallest Nanbeige 4.2 3B build; fits "
            "comfortably on an 8GB GPU (e.g. RX 7600), with plenty of headroom.",
            mac_tip="Needs ~7GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=8,
            memory=12,
            llamacpp_version=10159,
        ),
    ]
