"""Hardcoded Gemma4-26B-A4B GGUF catalog entries."""

from __future__ import annotations

from ._types import LocalLLMEntry


def gemma4_26b_a4b_entries() -> list[LocalLLMEntry]:
    return [
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-q8-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-Q8_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-Q8_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q8_K_XL",
            size_hint="27.6 GB",
            gpu_tip="~31GB total at 128K context. An 8GB GPU (e.g. RTX 4060) plus a 32GB DDR5 kit "
            "covers it comfortably — Gemma 4's MoE design (the A4B in its filename) lets llama.cpp "
            "offload inactive experts to RAM without much of a speed hit.",
            mac_tip="Needs ~31GB — fits a 48GB MacBook Pro (M4 Pro/Max or M5 Pro/Max) comfortably; "
            "a 32GB config is tight.",
            min_memory=32,
            memory=48,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-q6-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-Q6_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-Q6_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q6_K_XL",
            size_hint="23.3 GB",
            gpu_tip="~26GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus a 32GB DDR5 "
            "kit is enough — Gemma 4's MoE offloading (the A4B design) keeps this close to "
            "full-GPU speed.",
            mac_tip="Needs ~26GB — fits a 32GB MacBook Pro (M4 or M5) if you trim context a bit, "
            "or a 48GB config comfortably.",
            min_memory=32,
            memory=48,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-q5-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-Q5_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-Q5_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q5_K_XL",
            size_hint="21.2 GB",
            gpu_tip="~24GB total at 128K context. An 8GB GPU (e.g. RTX 5060) plus a 24GB DDR5 kit "
            "covers it — Gemma 4's MoE design offloads inactive experts to RAM without much of a "
            "speed hit.",
            mac_tip="Needs ~24GB — fits a 32GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=24,
            memory=32,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-q4-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-Q4_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-Q4_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q4_K_XL",
            size_hint="17.0 GB",
            gpu_tip="~20GB total at 128K context. An 8GB GPU (e.g. RTX 4060) plus ~24GB of DDR5 "
            "system RAM is enough — Gemma 4's MoE design (the A4B in its filename) lets llama.cpp "
            "offload inactive experts to RAM without much of a speed hit.",
            mac_tip="Needs ~20GB — fits a 32GB MacBook Pro (M4 or M5) comfortably; a 24GB config "
            "is tight.",
            min_memory=24,
            memory=32,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-qat-ud-q4-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B QAT UD-Q4_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-qat-GGUF",
            filename="gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="QAT-UD-Q4_K_XL",
            size_hint="14.2 GB",
            gpu_tip="~17GB total at 128K context. Any 8GB GPU (e.g. RTX 4060) plus a 24GB DDR5 "
            "kit is plenty — the QAT build barely needs the offloading trick at all.",
            mac_tip="Needs ~17GB — fits a 24GB MacBook Pro (M4, M4 Pro, M5, or M5 Pro) "
            "comfortably.",
            min_memory=24,
            memory=32,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-q3-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-Q3_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-Q3_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q3_K_XL",
            size_hint="12.9 GB",
            gpu_tip="~16GB total at 128K context. An 8GB GPU (e.g. RX 7600) plus a 16GB DDR5 kit "
            "covers it comfortably, with Gemma 4's MoE offloading filling in the gap.",
            mac_tip="Needs ~16GB — fits a 24GB MacBook Pro comfortably; a 16GB M5 is tight.",
            min_memory=16,
            memory=24,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-q2-k-xl",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-Q2_K_XL by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-Q2_K_XL.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-Q2_K_XL",
            size_hint="10.5 GB",
            gpu_tip="~14GB total at 128K context. An 8GB GPU (e.g. RTX 3060 Ti) plus a 16GB DDR5 "
            "kit is enough for this small a build.",
            mac_tip="Needs ~14GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=16,
            memory=16,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-iq4-xs",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-IQ4_XS by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-IQ4_XS.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-IQ4_XS",
            size_hint="13.6 GB",
            gpu_tip="~17GB total at 128K context. An 8GB GPU (e.g. RTX 4060) plus a 24GB DDR5 kit "
            "covers it comfortably via Gemma 4's MoE expert offloading.",
            mac_tip="Needs ~17GB — fits a 24GB MacBook Pro comfortably; a 16GB M5 is tight.",
            min_memory=16,
            memory=24,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-iq3-xxs",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-IQ3_XXS by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-IQ3_XXS.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-IQ3_XXS",
            size_hint="11.4 GB",
            gpu_tip="~14GB total at 128K context. An 8GB GPU (e.g. RX 7600) plus a 16GB DDR5 kit "
            "is enough, with llama.cpp's MoE offloading barely costing any speed.",
            mac_tip="Needs ~14GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=16,
            memory=16,
            llamacpp_version=8720,
        ),
        LocalLLMEntry(
            name="unsloth-gemma4-26b-a4b-ud-iq2-xxs",
            kind="hardcoded_hf",
            description="Gemma 4 26B A4B UD-IQ2_XXS by Unsloth",
            repo_id="unsloth/gemma-4-26B-A4B-it-GGUF",
            filename="gemma-4-26B-A4B-it-UD-IQ2_XXS.gguf",
            context_window=262_144,
            base_llm="Gemma4-26B-A4B",
            llm_author="Google DeepMind",
            quant_author="Unsloth",
            quant_type="UD-IQ2_XXS",
            size_hint="9.9 GB",
            gpu_tip="~13GB total at 128K context. Any 8GB GPU (e.g. RTX 5060) plus a 16GB DDR5 kit "
            "handles this, the smallest of the Gemma 4 26B A4B builds.",
            mac_tip="Needs ~13GB — fits a 16GB MacBook Pro (M4 or M5) comfortably.",
            min_memory=16,
            memory=16,
            llamacpp_version=8720,
        ),
    ]
