"""``toolchain_build`` tool — runs a project's generated build scripts.

Executes ``scripts/<step>.sh`` (POSIX) or ``scripts/<step>.ps1`` (Windows) at
the project root named by the mandatory ``project_path`` input, in canonical
order (format → build → static_analysis → test), stopping at the first
failure. The caller supplies ``project_path`` (the directory holding the
project's ``.kodo/`` dir) rather than relying on a bound project — Problem
Solver runs have none, and any kodo project on disk is buildable. The scripts
themselves are generated by a toolchain-setup sub-agent (see
``base_toolchain.md``) — this tool only executes them and reports a clear
error when one hasn't been generated yet.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from ._search import UtilTimeout, run_util
from ._tool import Tool

__all__ = ["ToolchainBuildTool"]

_log = logging.getLogger(__name__)

_POSIX = os.name == "posix"
_BUILD_TIMEOUT = 600.0

# Canonical order; `format` defaults off (it mutates source in place).
_STEPS: tuple[str, ...] = ("format", "build", "static_analysis", "test")
_DEFAULTS: dict[str, bool] = {
    "format": False,
    "build": True,
    "static_analysis": True,
    "test": True,
}


class ToolchainBuildTool(Tool):
    """Run the enabled build steps via the project's generated scripts."""

    async def handle(self, tool_input: dict[str, object]) -> str:
        raw_project_path = str(tool_input.get("project_path", "")).strip()
        if not raw_project_path:
            return json.dumps(
                {"error": "project_path is required: the project root directory to build."}
            )
        # Absolute paths are taken as-is — any kodo project on disk is
        # buildable, bound or not. Relative paths get the run's normal
        # resolution (project-relative in Guided, workspace-folder-anchored in
        # Problem Solver) so agents that only know relative paths can build.
        candidate = Path(raw_project_path)
        if candidate.is_absolute():
            project_root = candidate.resolve()
        else:
            try:
                project_root = self.context.resolver.resolve(raw_project_path)
            except PermissionError as exc:
                return json.dumps({"error": str(exc)})

        test_selector = tool_input.get("test_selector")
        scripts_dir = project_root / "scripts"

        results: list[dict[str, object]] = []
        success = True
        for step in _STEPS:
            enabled = tool_input.get(step)
            if not (enabled if enabled is not None else _DEFAULTS[step]):
                continue
            script = self.__script_path(scripts_dir, step)
            if script is None:
                ext = "sh" if _POSIX else "ps1"
                results.append(
                    {
                        "step": step,
                        "success": False,
                        "log": (
                            f"No script found at scripts/{step}.{ext}. Ask the toolchain-setup "
                            "agent (e.g. toolchain_python) to generate it first."
                        ),
                    }
                )
                success = False
                break
            try:
                exit_code, stdout, stderr = await self.__run_script(
                    script, test_selector if step == "test" else None, project_root
                )
            except (UtilTimeout, OSError) as exc:
                results.append({"step": step, "success": False, "log": str(exc)})
                success = False
                break
            log = (stdout + stderr).decode("utf-8", errors="replace")
            step_success = exit_code == 0
            results.append({"step": step, "success": step_success, "log": log})
            if not step_success:
                success = False
                break

        return json.dumps({"success": success, "steps": results})

    @staticmethod
    def __script_path(scripts_dir: Path, step: str) -> Path | None:
        candidate = scripts_dir / (f"{step}.sh" if _POSIX else f"{step}.ps1")
        return candidate if candidate.is_file() else None

    @staticmethod
    async def __run_script(
        script: Path, test_selector: object, project_root: Path
    ) -> tuple[int | None, bytes, bytes]:
        if _POSIX:
            binary = str(script)
            args = [str(test_selector)] if test_selector else []
        else:
            binary = "powershell"
            args = ["-File", str(script)] + ([str(test_selector)] if test_selector else [])
        _log.info("toolchain_build running %s %s", binary, args)
        return await run_util(binary, args, str(project_root), timeout=_BUILD_TIMEOUT)
