"""LLM plugin interfaces and Anthropic implementation."""

from ._cloud_registry import (
    CloudLLMEntry,
    get_cloud_entry,
    get_cloud_registry,
    get_cloud_vendor_display_name,
    get_cloud_vendor_module,
)
from ._context import get_context_window
from ._gateway import EventSink, LLMGateway, LLMRouting
from ._hardware import detect_ram_gb, detect_vram_gb
from ._interface import (
    LLMPlugin,
    Message,
    RateLimited,
    StreamEvent,
    ThinkingDelta,
    ThinkingSignature,
    TokenDelta,
    ToolCallArgDelta,
    ToolCallEvent,
    ToolSpec,
    TurnEnd,
    Usage,
    default_cache_breakpoints,
)
from ._local_registry import (
    GPT_OSS_REASONING_EFFORT_FAMILY,
    QWEN_REASONING_BUDGET_FAMILY,
    QWEN_TIER_TOKEN_BUDGETS,
    REASONING_BUDGET_MESSAGE,
    LlamaFlavor,
    LocalLLMEntry,
    add_flavor,
    add_local_entry,
    clear_llama_server_override_path,
    get_active_flavor,
    get_effective_flavor_id,
    get_flavors,
    get_llama_server_override_path,
    get_local_registry,
    local_thinking_default_tier,
    local_thinking_family,
    local_thinking_tiers,
    parse_llama_args,
    parse_llama_args_text,
    remove_flavor,
    remove_local_entry,
    resolve_context_window,
    resolve_effective_llama_config,
    set_active_flavor,
    set_llama_server_override_path,
    update_flavor,
)
from ._logger import LoggingLLMPlugin
from ._sanitize import strip_kodo_callouts
from ._tool_logger import ToolCallLogger

__all__ = [
    "CloudLLMEntry",
    "EventSink",
    "GPT_OSS_REASONING_EFFORT_FAMILY",
    "LLMGateway",
    "LLMPlugin",
    "LLMRouting",
    "LlamaFlavor",
    "LocalLLMEntry",
    "LoggingLLMPlugin",
    "Message",
    "QWEN_REASONING_BUDGET_FAMILY",
    "QWEN_TIER_TOKEN_BUDGETS",
    "REASONING_BUDGET_MESSAGE",
    "RateLimited",
    "ThinkingDelta",
    "ThinkingSignature",
    "ToolCallLogger",
    "ToolSpec",
    "Usage",
    "StreamEvent",
    "TokenDelta",
    "ToolCallArgDelta",
    "ToolCallEvent",
    "TurnEnd",
    "add_flavor",
    "add_local_entry",
    "clear_llama_server_override_path",
    "default_cache_breakpoints",
    "detect_ram_gb",
    "detect_vram_gb",
    "get_active_flavor",
    "get_cloud_entry",
    "get_cloud_registry",
    "get_cloud_vendor_display_name",
    "get_cloud_vendor_module",
    "get_context_window",
    "get_effective_flavor_id",
    "get_flavors",
    "get_llama_server_override_path",
    "get_local_registry",
    "local_thinking_default_tier",
    "local_thinking_family",
    "local_thinking_tiers",
    "parse_llama_args",
    "parse_llama_args_text",
    "remove_flavor",
    "remove_local_entry",
    "resolve_context_window",
    "resolve_effective_llama_config",
    "set_active_flavor",
    "set_llama_server_override_path",
    "strip_kodo_callouts",
    "update_flavor",
]
