"""LLM plugin interfaces and Anthropic implementation."""

from ._arg_catalog import LLAMA_ARG_CATALOG, LlamaArgSpec, llama_arg_catalog_to_json
from ._cloud_registry import (
    CloudLLMEntry,
    get_cloud_entry,
    get_cloud_registry,
    get_cloud_vendor_display_name,
    get_cloud_vendor_module,
)
from ._context import get_context_window
from ._gateway import EventSink, LLMGateway, LLMRouting
from ._hardware import detect_ram_gb, detect_vram_gb
from ._interface import (
    LLMPlugin,
    Message,
    RateLimited,
    StreamEvent,
    ThinkingDelta,
    ThinkingSignature,
    TokenDelta,
    ToolCallArgDelta,
    ToolCallEvent,
    ToolSpec,
    TurnEnd,
    Usage,
    default_cache_breakpoints,
)
from ._logger import LoggingLLMPlugin
from ._openrouter_catalog import (
    OpenRouterModelInfo,
    get_openrouter_catalog,
    get_openrouter_model,
    refresh_openrouter_catalog,
    run_openrouter_catalog_refresh_loop,
)
from ._provider_retry import RetryExhaustedError, UnrecoverableError
from ._sampling import (
    RESERVED_SAMPLING_FIELDS,
    SAMPLER_NAMES,
    SAMPLING_PARAM_SPECS,
    SamplingParams,
    SamplingParamSpec,
    sampling_param_spec,
    sampling_specs_to_json,
)
from ._sanitize import strip_kodo_callouts
from ._tool_logger import ToolCallLogger
from .local_registry import (
    BASE_LLAMA_ARGS,
    GPT_OSS_REASONING_EFFORT_FAMILY,
    QWEN_REASONING_BUDGET_FAMILY,
    QWEN_TIER_TOKEN_BUDGETS,
    REASONING_BUDGET_MESSAGE,
    RESERVED_LLAMA_ARGS,
    SHARED_KNOBS,
    KnobKind,
    KnobOption,
    LlamaKnob,
    LlmProfile,
    LocalLLMEntry,
    add_local_entry,
    add_profile,
    clear_llama_server_override_path,
    get_active_profile,
    get_knob_selections,
    get_llama_server_override_path,
    get_local_registry,
    get_profiles,
    knob_owned_flags,
    knob_selection_args,
    local_thinking_default_tier,
    local_thinking_family,
    local_thinking_tiers,
    parse_llama_args,
    parse_llama_args_text,
    remove_local_entry,
    remove_profile,
    resolve_context_window,
    resolve_default_profile_args,
    resolve_effective_llama_config,
    resolve_knob_selections,
    set_active_profile,
    set_knobs,
    set_llama_server_override_path,
    strip_reserved_llama_args,
    update_profile,
    validate_knobs,
)

__all__ = [
    "BASE_LLAMA_ARGS",
    "CloudLLMEntry",
    "EventSink",
    "GPT_OSS_REASONING_EFFORT_FAMILY",
    "LLAMA_ARG_CATALOG",
    "LLMGateway",
    "LLMPlugin",
    "LLMRouting",
    "KnobKind",
    "KnobOption",
    "LlamaArgSpec",
    "LlamaKnob",
    "LlmProfile",
    "LocalLLMEntry",
    "LoggingLLMPlugin",
    "Message",
    "OpenRouterModelInfo",
    "QWEN_REASONING_BUDGET_FAMILY",
    "QWEN_TIER_TOKEN_BUDGETS",
    "REASONING_BUDGET_MESSAGE",
    "RESERVED_LLAMA_ARGS",
    "RESERVED_SAMPLING_FIELDS",
    "RateLimited",
    "RetryExhaustedError",
    "SAMPLER_NAMES",
    "SAMPLING_PARAM_SPECS",
    "SHARED_KNOBS",
    "SamplingParamSpec",
    "SamplingParams",
    "StreamEvent",
    "ThinkingDelta",
    "ThinkingSignature",
    "TokenDelta",
    "ToolCallArgDelta",
    "ToolCallEvent",
    "ToolCallLogger",
    "ToolSpec",
    "TurnEnd",
    "UnrecoverableError",
    "Usage",
    "add_local_entry",
    "add_profile",
    "clear_llama_server_override_path",
    "default_cache_breakpoints",
    "detect_ram_gb",
    "detect_vram_gb",
    "get_active_profile",
    "get_cloud_entry",
    "get_cloud_registry",
    "get_cloud_vendor_display_name",
    "get_cloud_vendor_module",
    "get_context_window",
    "get_knob_selections",
    "get_llama_server_override_path",
    "get_local_registry",
    "get_openrouter_catalog",
    "get_openrouter_model",
    "get_profiles",
    "knob_owned_flags",
    "knob_selection_args",
    "llama_arg_catalog_to_json",
    "local_thinking_default_tier",
    "local_thinking_family",
    "local_thinking_tiers",
    "parse_llama_args",
    "parse_llama_args_text",
    "refresh_openrouter_catalog",
    "remove_local_entry",
    "remove_profile",
    "resolve_context_window",
    "resolve_default_profile_args",
    "resolve_effective_llama_config",
    "resolve_knob_selections",
    "run_openrouter_catalog_refresh_loop",
    "sampling_param_spec",
    "sampling_specs_to_json",
    "set_active_profile",
    "set_knobs",
    "set_llama_server_override_path",
    "strip_kodo_callouts",
    "strip_reserved_llama_args",
    "update_profile",
    "validate_knobs",
]
