"""Prompt file-attachments: control-tag parsing, validation, and injection.

Attachments ride the ordinary ``prompt.submit`` ``text`` field as a single
machine-generated control-tag line that the VS Code extension prepends ahead of
the user's prompt::

    <!--KODO_ATTACHMENTS:["/abs/path/a.py","/abs/path/b.md"]-->
    <the user's actual prompt>

The server (and only the server) is responsible for the attachment lifecycle:

1. :func:`parse_attachment_marker` splits the control line off the prompt,
   yielding the clean prompt text plus the list of absolute source paths.
2. :func:`load_attachment` reads + validates one source file (text-only, size
   capped) so its content can be (a) copied into the session's own storage and
   (b) injected into the LLM prompt.
3. :func:`inject_attachments` rebuilds the *expanded* prompt the LLM sees —
   each file under a ``## Attached file: <name>`` heading, the user's prompt
   last. This exact format is reused on resume (re-reading the session's stored
   copies) so the reconstructed LLM context is byte-identical to submit time.

What is **never** done here: writing file content into ``session.jsonl``. The
engine persists only the clean prompt plus opaque links to the stored copies
(see :class:`~kodo.state.TransientStore.store_attachment`); the content lives in
the session's ``attachments/`` directory, so the session stays intact even if
the original file is later moved or deleted.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass

__all__ = [
    "MAX_ATTACHMENTS",
    "MAX_ATTACH_BYTES",
    "AttachmentError",
    "LoadedAttachment",
    "parse_attachment_marker",
    "encode_attachment_marker",
    "load_attachment",
    "inject_attachments",
]

# Mirrors the limits the extension pre-checks at attach time; the server is the
# authoritative gate (the original file may have changed between attach and
# submit, so it is re-read and re-validated here).
MAX_ATTACHMENTS = 9
MAX_ATTACH_BYTES = 128 * 1024

_MARKER_PREFIX = "<!--KODO_ATTACHMENTS:"
_MARKER_SUFFIX = "-->"


class AttachmentError(Exception):
    """A source file could not be used as a text attachment.

    The message is user-facing (surfaced as a recoverable error event) and
    explains why the file was rejected (missing, binary, or too large).
    """


def parse_attachment_marker(text: str) -> tuple[str, list[str]]:
    """Split a leading attachment control line off a submitted prompt.

    The control line (if present) is always the first line and is wholly
    machine-generated by the extension, so it is matched exactly: the first
    line must start with ``<!--KODO_ATTACHMENTS:``, end with ``-->``, and the
    text between must be a JSON array of absolute path strings. Anything else
    (including a malformed array) is treated as an ordinary prompt with no
    attachments — the text is returned untouched.

    Args:
        text: The raw ``prompt.submit`` text.

    Returns:
        tuple[str, list[str]]: ``(clean_prompt, source_paths)``. ``source_paths``
        is empty when no valid control line is present.
    """
    newline = text.find("\n")
    first_line = text if newline == -1 else text[:newline]
    if not (first_line.startswith(_MARKER_PREFIX) and first_line.endswith(_MARKER_SUFFIX)):
        return text, []
    body = first_line[len(_MARKER_PREFIX) : -len(_MARKER_SUFFIX)]
    try:
        parsed = json.loads(body)
    except json.JSONDecodeError:
        return text, []
    if not isinstance(parsed, list):
        return text, []
    paths = [p for p in parsed if isinstance(p, str) and p]
    rest = "" if newline == -1 else text[newline + 1 :]
    return rest, paths


def encode_attachment_marker(paths: list[str]) -> str:
    """Build the control line for *paths* (kept here so both ends share a format).

    Returned without a trailing newline; callers join it to the prompt with one.
    Used by tests; the extension builds the identical string in TypeScript.
    """
    return f"{_MARKER_PREFIX}{json.dumps(paths)}{_MARKER_SUFFIX}"


@dataclass(frozen=True)
class LoadedAttachment:
    """One validated source file, ready to copy into the session + inject."""

    name: str
    content: str
    size: int


def load_attachment(path: str, *, running_total: int) -> LoadedAttachment:
    """Read and validate one source file as a UTF-8 text attachment.

    Args:
        path: Absolute path to the source file.
        running_total: Bytes already accepted for this prompt's attachments, so
            the combined cap can be enforced across files.

    Returns:
        LoadedAttachment: The basename, decoded text, and byte size.

    Raises:
        AttachmentError: If the file is missing/unreadable, is not valid UTF-8
            text (a NUL byte or a decode failure), exceeds the per-file cap, or
            would push the combined attachment size over the cap.
    """
    name = os.path.basename(path) or path
    try:
        with open(path, "rb") as fh:
            raw = fh.read()
    except OSError as exc:
        raise AttachmentError(
            f'Attached file "{name}" could not be read and was skipped ({exc.strerror or exc}).'
        ) from exc
    if b"\x00" in raw:
        raise AttachmentError(
            f'Attached file "{name}" appears to be binary (it was skipped). '
            "Only text files can be attached."
        )
    try:
        content = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise AttachmentError(
            f'Attached file "{name}" is not valid UTF-8 text (it was skipped). '
            "Only text files can be attached."
        ) from exc
    size = len(raw)
    if size > MAX_ATTACH_BYTES:
        raise AttachmentError(
            f'Attached file "{name}" is larger than 128 KB (it was skipped).'
        )
    if running_total + size > MAX_ATTACH_BYTES:
        raise AttachmentError(
            f'Attached file "{name}" was skipped — the combined size of attached '
            "files would exceed the 128 KB limit."
        )
    return LoadedAttachment(name=name, content=content, size=size)


def inject_attachments(clean_text: str, items: list[tuple[str, str]]) -> str:
    """Build the expanded prompt the LLM sees from attachment ``(name, content)``.

    Each file is rendered under a ``## Attached file: <name>`` heading, the
    user's prompt last, blocks joined by blank lines. This is the single source
    of truth for the injection layout so submit-time and resume-time
    reconstructions match exactly.

    Args:
        clean_text: The user's prompt with the control line already stripped.
        items: ``(display_name, text_content)`` for each stored attachment, in
            attachment order.

    Returns:
        str: The expanded prompt, or ``clean_text`` unchanged when there are no
        attachments.
    """
    if not items:
        return clean_text
    parts = [f"## Attached file: {name}\n{content}" for name, content in items]
    parts.append(clean_text)
    return "\n\n".join(parts)
